export * from './app.component';
export * from './login.component';
export * from './exercise.component';
export * from './loading-indicator';
export * from './register.componet';
export * from './dashboard.componet';
export * from './nav.component';
export * from './class.component';
export * from './livesearch/livesearch.component'
